# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160329_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chice_text',
            new_name='choice_text',
        ),
    ]
